export default {
    altaArticulos:{
        post:{
            tags:['Articulos'],
            summary:'Crear un nuevo articulo',
            security: [  // ⬅️ Aplica el esquema de seguridad
                {
                    bearerAuth: []
                }
            ],
            requestBody:{
                content:{
                    'application/json':{
                        schema:{
                            type:'object',
                            properties:{
                                nombre:{
                                    type:'string'
                                },
                                precio_costo:{
                                    type:'number'
                                },
                                precio_venta:{
                                    type:'number'
                                },
                                categoria_articulo:{
                                    type:'number'
                                },
                                cantidad:{
                                    type:'number'
                                },
                                sku:{
                                    type:'string'
                                }
                            }
                        }
                    }
                }
            },
            responses:{
                200:{
                    "description":"Articulo creado",
                    content:{
                        'application/json':{
                            schema:{
                                type:'object',
                                properties:{
                                    info:{
                                        type:'boolean'
                                    },
                                    msg:{
                                        type:'string'
                                    },
                                    response:{
                                        type:'array',
                                        items:{
                                            type:'object',
                                            properties:{
                                                id:{
                                                    type:'number'
                                                },
                                                nombre:{
                                                    type:'string'
                                                },
                                                precio_costo:{
                                                    type:'number'
                                                },
                                                precio_venta:{
                                                    type:'number'
                                                },
                                                categoria_articulo:{
                                                    type:'number'
                                                },
                                                cantidad:{
                                                    type:'number'
                                                },
                                                sku:{
                                                    type:'string'
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
