export default {
    insertCarta:{
        post:{
            tags:['Carta'],
            summary:'Insertar carta',
            description:'Inserta una carta en la base de datos',
            security:[
                {
                    bearerAuth:[]
                }
            ],
            requestBody:{
                content:{
                    'application/json':{
                        schema:{
                            type:'object',
                            properties:{
                                nombre:{
                                    type:'string'
                                },
                                precio_costo:{
                                    type:'number'
                                },
                                precio_venta:{
                                    type:'number'
                                },
                                descripcion:{
                                    type:'string'
                                },
                                sku:{
                                    type:'string'
                                },
                                categoria:{
                                    type:'string'
                                },
                                ingredientes:{
                                    type:'array',
                                    items:{
                                        type:'object',
                                        properties:{
                                            id:{
                                                type:'number'
                                            },
                                            nombre:{
                                                type:'string'
                                            },
                                            sku:{
                                                type:'string'
                                            },
                                            valor_modulo:{
                                                type: 'string'
                                            },
                                            cantidad:{
                                                type:'number'
                                            }
                                        }
                                    }
                                },
                                ganancia:{
                                    type:'number'
                                }
                            }
                        }
                    }
                }
            },
            responses:{
                200:{
                    description:'Carta creada',
                    content:{
                        'application/json':{
                            schema:{
                                type:'object',
                                properties:{
                                    info:{
                                        type:'boolean'
                                    },
                                    msg:{
                                        type:'string'
                                    },
                                    content:{
                                        type:'string'
                                    }
                                }
                            }
                        }
                    }
                },
                400:{
                    description:'Error al crear la carta',
                    content:{
                        'application/json':{
                            schema:{
                                type:'object',
                                properties:{
                                    info:{
                                        type:'boolean'
                                    },
                                    msg:{
                                        type:'string'
                                    },
                                    content:{
                                        type:'null'
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }    
}